[tools]
# Go version from your go.mod file
go = "1.25.3"

# Node.js for JavaScript/TypeScript
node = "24.10.0"
npm = "11.5.1"

# Pre-commit for Git hooks
pre-commit = "4.3.0"

# Additional tools for development
golangci-lint = "2.6.2"
goreleaser = "2.12.0"
kind = "0.30.0"
kubectl = "1.34.1"
markdownlint-cli2 = "0.18.1"

# code-generators
swag = "1.8.7"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "0.17.2"
protoc = "latest"
protoc-gen-go = "latest"

[env]
# Set environment variables for Go development
GO111MODULE = "on"

# Vue.js related environment variables
NODE_ENV = "development"
